---
title: "Control de calidad de archivos fastq"
author: "Estefania Mancini"
date: "Marzo 2022"
output:
    html_document:
    toc: true # table of content true
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: true  ## if you want number sections at each table header
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Control de calidad de secuencias

Utilizaremos el paquete [ShortRead](http://bioconductor.org/packages/release/bioc/html/ShortRead.html)

También hay otras opciones disponibles como:
[FastQC](https://www.bioinformatics.babraham.ac.uk/projects/fastqc/)

```{r ShortRead, echo=TRUE, eval=FALSE}
library(ShortRead)
setwd("../data/")
fqQC <-qa("R1.fastq")
report(fqQC, type="html", dest="fastqQC_R1")
fqQC2 <-qa("R2.fastq")
report(fqQC2, type="html", dest="fastqQC_R2")
```

## Preguntas

* Que podemos observar?
* Cual es la longitud de los reads
* Es la calidad de ambos reads similar
* Hay algun patron de secuencia que nos llame la atencion